/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'source' : Source,
  'tags' : Array<string>,
  'publishedAt' : Timestamp,
  'isBreaking' : boolean,
  'author' : string,
  'summary' : string,
  'imageUrl' : [] | [string],
  'visible' : boolean,
  'category' : Category,
}
export type Category = { 'entertainment' : null } |
  { 'national' : null } |
  { 'local' : null } |
  { 'technology' : null } |
  { 'business' : null } |
  { 'sports' : null } |
  { 'world' : null } |
  { 'health' : null } |
  { 'politics' : null };
export type Source = { 'auto' : null } |
  { 'manual' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<
    [
      string,
      string,
      string,
      Category,
      string,
      [] | [string],
      Array<string>,
      boolean,
    ],
    bigint
  >,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'fetchAndImportExternalNews' : ActorMethod<[], undefined>,
  'getArticle' : ActorMethod<[bigint], Article>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setBreakingNews' : ActorMethod<[bigint, boolean], undefined>,
  'toggleArticleVisibility' : ActorMethod<[bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArticle' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Category,
      string,
      [] | [string],
      Array<string>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];