/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'entertainment' : IDL.Null,
  'national' : IDL.Null,
  'local' : IDL.Null,
  'technology' : IDL.Null,
  'business' : IDL.Null,
  'sports' : IDL.Null,
  'world' : IDL.Null,
  'health' : IDL.Null,
  'politics' : IDL.Null,
});
export const Source = IDL.Variant({ 'auto' : IDL.Null, 'manual' : IDL.Null });
export const Timestamp = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'source' : Source,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : Timestamp,
  'isBreaking' : IDL.Bool,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'visible' : IDL.Bool,
  'category' : Category,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'fetchAndImportExternalNews' : IDL.Func([], [], []),
  'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setBreakingNews' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'toggleArticleVisibility' : IDL.Func([IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateArticle' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'entertainment' : IDL.Null,
    'national' : IDL.Null,
    'local' : IDL.Null,
    'technology' : IDL.Null,
    'business' : IDL.Null,
    'sports' : IDL.Null,
    'world' : IDL.Null,
    'health' : IDL.Null,
    'politics' : IDL.Null,
  });
  const Source = IDL.Variant({ 'auto' : IDL.Null, 'manual' : IDL.Null });
  const Timestamp = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'source' : Source,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : Timestamp,
    'isBreaking' : IDL.Bool,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'visible' : IDL.Bool,
    'category' : Category,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'fetchAndImportExternalNews' : IDL.Func([], [], []),
    'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setBreakingNews' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'toggleArticleVisibility' : IDL.Func([IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateArticle' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };